language: objective-c
osx_image: xcode12.2

before_install:
  - Frameworks/gethamcrest
  - gem install slather

script:
  - set -o pipefail;
  - xcodebuild build -project Source/OCMockito.xcodeproj -scheme OCMockito-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,OS=latest,name=iPhone 8" | xcpretty
  - xcodebuild build -project Source/OCMockito.xcodeproj -scheme OCMockito-tvOS -sdk appletvsimulator -destination "platform=tvOS Simulator,OS=latest,name=Apple TV" | xcpretty
  - xcodebuild build -project Source/OCMockito.xcodeproj -scheme OCMockito-watchOS -sdk watchsimulator -destination "platform=watchOS Simulator,OS=latest,name=Apple Watch Series 5 - 44mm" | xcpretty
  - xcodebuild test -project Source/OCMockito.xcodeproj -scheme OCMockito -sdk macosx | xcpretty
  - pod spec lint --quick

after_success:
  - slather
